services:
    wsse.security.authentication.provider:
        class: Sfynx\WsseBundle\Security\Authentication\Provider\WsseProvider
        arguments: ['', "%sfynx.wsse.security.cache_dir%", @service_container]  

    wsse.security.authentication.listener:
        class: Sfynx\WsseBundle\Security\Firewall\WsseListener
        arguments: [@security.context, @security.authentication.manager, @logger]
        tags:
            - { name: monolog.logger, channel: wsse }

